---

template: Hello, %s!

defaultName: Stranger

logging:
  level: INFO
  loggers:
    twitter: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: football8
  url: jdbc:mysql://localhost:3306/micro_blog
